# pipeline type: long or hybrid
pipeline: [hybrid]
# # insert path to the input folder - raw reads
input_shortreads: [/path/to/short/reads]
input_longreads: [/path/to/long/reads]
# insert path to the output folder
output: [/path/to/output/folder]
# insert the name of the strains
# e.g.  strains: [15DD0163, 11DD0261, ... ]
strains: [strain01, strain02, strain03, ...]