# insert path to the folder for saving all generated data
path: [/mnt/prostlocal2/projects/st_mycoplasma_assembly/doubice_hybrid]
# insert the name of the strains to the corresponding barcodes e.g.:  barcode01: strain01, barcode02: strain02, ...
strains: {barcode01: barcode01, barcode02: barcode02, barcode03: barcode03, barcode04: barcode04, barcode05: barcode05, barcode06: barcode06, barcode07: barcode07, barcode08: barcode08, barcode09: barcode09, barcode10: 15DD0163, barcode11: 17DD0007, barcode12: 17DD0020}
# strains: [14-2711]
preprocessing_short: [fastp, trimmomatic]
preprocessing_long: [filtlong]
demultiplexing: [guppy]
assembly: [flye]
postprocessing: [racon, medaka]
quality: [fastqc, nanoplot, quast]
